services:
  - type: web
    name: meeseeker
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000